name: Build and test a unity3d project

on: [push]

jobs:
  # get_license:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: gableroux/unity3d:2019.1.14f1
  #     volumes:
  #       - .:/project

  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: get license
  #     run: ./ci/get_license.sh

  test:
    strategy:
      matrix:
        platform: [editmode, playmode]
    runs-on: ubuntu-latest
    container:
      image: gableroux/unity3d:2019.1.14f1
      volumes:
        - .:/project
      env:
        TEST_PLATFORM: ${{ matrix.platform }}
        # cannot use license here, leads to Unrecognized named-value: 'secrets'
        # UNITY_LICENSE_CONTENT: ${{ secrets.UNITY_LICENSE_CONTENT }}

    steps:
      - uses: actions/checkout@v1
      - name: before script
        env:
          UNITY_LICENSE_CONTENT: ${{ secrets.UNITY_LICENSE_CONTENT }}
        run: ./ci/before_script.sh
      - name: test
        run: ./ci/test.sh

  build:
    strategy:
      matrix:
        target: [StandaloneWindows64, WebGL, StandaloneLinux64]
    runs-on: ubuntu-latest
    container:
      image: gableroux/unity3d:2019.1.14f1
      volumes:
        - .:/project
      env:
        BUILD_TARGET: ${{ matrix.target }}
        # UNITY_LICENSE_CONTENT: ${{ secrets.UNITY_LICENSE_CONTENT }}

    steps:
      - uses: actions/checkout@v1
      - name: before script
        env:
          UNITY_LICENSE_CONTENT: ${{ secrets.UNITY_LICENSE_CONTENT }}
        run: ./ci/before_script.sh
      - name: build
        run: ./ci/build.sh
      - uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: ./Builds/
